name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-linters-and-tests:
    name: Run Linters and Tests
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2
        with:
          fetch-depth: 1


      - name: Setup Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-django pytest-xdist black flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          black: true
          black_args: "--exclude migrations/"
          auto_fix: true


      - name: Test with pytest
        env:
          DJANGO_SETTINGS_MODULE: market.test_settings
        run: |
          pytest --cov ./ -n 2 --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          files: ./coverage1.xml,./coverage2.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true


